# Generated by Django 3.2.9 on 2022-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='chois',
            field=models.CharField(choices=[('number', 'հեռախոսահամար'), ('email', 'Ել․հասցե'), ('addres', 'Հասցե')], max_length=15, verbose_name='Տեսակ'),
        ),
    ]
