# Generated by Django 3.2.9 on 2022-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contacts_chois'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(verbose_name='URL-հասցե')),
                ('chois', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('telegarm', 'telegarm')], max_length=15, verbose_name='Ցանկ')),
            ],
            options={
                'verbose_name': 'Սոցցանց',
                'verbose_name_plural': 'Սոցցանցեր',
            },
        ),
    ]
