# Generated by Django 3.2.9 on 2022-02-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='slide')),
            ],
            options={
                'verbose_name': 'Սլայդ',
                'verbose_name_plural': 'Սլայդներ',
            },
        ),
    ]
