# Generated by Django 3.2.9 on 2022-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='file',
        ),
        migrations.AddField(
            model_name='slide',
            name='slide',
            field=models.ImageField(default=1, upload_to='slide'),
            preserve_default=False,
        ),
    ]
