# Generated by Django 3.2.9 on 2022-02-28 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220210_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='վերնագր')),
                ('text', ckeditor.fields.RichTextField(verbose_name='տեքստ')),
                ('image', models.ImageField(upload_to='Welcom', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Գլխաոր',
                'verbose_name_plural': 'Գլխաոր',
            },
        ),
    ]
