# Generated by Django 3.2.9 on 2022-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_welcom_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Անուն')),
                ('categoris', models.CharField(max_length=100, verbose_name='մասնագիտություն')),
                ('image', models.ImageField(upload_to='Doctors', verbose_name='նկար')),
            ],
            options={
                'verbose_name': 'Բժիշկ',
                'verbose_name_plural': 'Բժիշկներ',
            },
        ),
    ]
