# Generated by Django 3.2.9 on 2022-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_doctors_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='կատեգորյայի-անվանում')),
                ('text', models.TextField(verbose_name='գլխաոր-տեքստ')),
                ('Paragraphtext', models.CharField(max_length=165, verbose_name='յեկրորտական-տքստ')),
                ('file', models.FileField(upload_to='category', verbose_name='նկար կամ վիդեո')),
                ('slug', models.SlugField(verbose_name='URI')),
            ],
            options={
                'verbose_name': 'կատեգորյա',
                'verbose_name_plural': 'կատեգորյաներ',
            },
        ),
    ]
