# Generated by Django 3.2.9 on 2022-03-01 08:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='գլխաոր-տեքստ'),
        ),
    ]
