# Generated by Django 3.2.9 on 2022-03-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Post', verbose_name='նկար կամ վիդեո')),
                ('title', models.CharField(max_length=100, verbose_name='նյութի վերնագիր')),
                ('text', models.TextField(verbose_name='Նյութի բովանդակություն')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='ժամանակ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KeyCategori', to='main.category', verbose_name='Կատեգորյաներ')),
                ('doctory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KeyDoctots', to='main.doctors', verbose_name='բժիշկը')),
            ],
            options={
                'verbose_name': 'Գլախաոր-Փոստ',
                'verbose_name_plural': 'Գլախաոր-Փոստ',
            },
        ),
    ]
