# Generated by Django 3.2.9 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Անվանում')),
                ('message', models.TextField(verbose_name='մաեկնաբանություն')),
                ('image', models.ImageField(upload_to='comment', verbose_name='նակար')),
            ],
            options={
                'verbose_name': 'Քոմոնթ',
                'verbose_name_plural': 'Քոմոնթնոր',
            },
        ),
    ]
