# Generated by Django 3.2.9 on 2022-03-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
