# Generated by Django 3.2.9 on 2022-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='button',
            field=models.BooleanField(default=False, verbose_name='Հաստատել'),
        ),
    ]
