# Generated by Django 3.2.9 on 2022-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_comment_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Կոմենտ', 'verbose_name_plural': 'Կոմենտներ'},
        ),
        migrations.AddField(
            model_name='post',
            name='rec',
            field=models.BooleanField(default=False, verbose_name='գլխաոր-նյութում'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='comment', verbose_name='նակար'),
        ),
    ]
