# Generated by Django 3.2.9 on 2022-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
