# Generated by Django 3.2.9 on 2022-03-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='կատեգորյա')),
            ],
            options={
                'verbose_name': 'Ապրանքիկատեգորյա',
                'verbose_name_plural': 'Ապրանքիկատեգորյաներ',
            },
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=17, verbose_name='վերնագիր')),
                ('price', models.SmallIntegerField(verbose_name='արժեք')),
                ('image', models.ImageField(upload_to='shop', verbose_name='Նկար')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.shopcategory')),
            ],
            options={
                'verbose_name': 'Ապրանք',
                'verbose_name_plural': 'Ապրանքներ',
            },
        ),
    ]
