# Generated by Django 3.2.9 on 2022-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_pagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='category',
            field=models.CharField(choices=[('news', 'news'), ('shop', 'shop')], max_length=100, verbose_name='նշեք էջը'),
        ),
    ]
