# Generated by Django 3.2.9 on 2022-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_pagetext_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('shop', 'Shop')], max_length=100, verbose_name='նշեք էջը'),
        ),
    ]
