# Generated by Django 3.2.9 on 2022-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_pagetext_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetext',
            old_name='category',
            new_name='categoryi',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='text',
            new_name='texti',
        ),
    ]
