# Generated by Django 3.2.9 on 2022-03-10 17:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_pagetext_categoryi'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='categoris_en',
            field=models.CharField(max_length=100, null=True, verbose_name='մասնագիտություն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='categoris_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='մասնագիտություն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='categoris_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='մասնագիտություն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='categoris_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='մասնագիտություն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='նկարագիր'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='text_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='նկարագիր'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='text_hy',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='նկարագիր'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='նկարագիր'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Անուն'),
        ),
    ]
