# Generated by Django 3.2.9 on 2022-03-11 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220310_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Նյութի բովանդակություն'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Նյութի բովանդակություն'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hy',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Նյութի բովանդակություն'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Նյութի բովանդակություն'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='նյութի վերնագիր'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='նյութի վերնագիր'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='նյութի վերնագիր'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='նյութի վերնագիր'),
        ),
    ]
