# Generated by Django 3.2.9 on 2022-03-11 13:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20220311_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcom',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='տեքստ'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='text_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='տեքստ'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='text_hy',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='տեքստ'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='տեքստ'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='title_en',
            field=models.CharField(max_length=68, null=True, verbose_name='վերնագր'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='title_fa',
            field=models.CharField(max_length=68, null=True, verbose_name='վերնագր'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='title_hy',
            field=models.CharField(max_length=68, null=True, verbose_name='վերնագր'),
        ),
        migrations.AddField(
            model_name='welcom',
            name='title_ru',
            field=models.CharField(max_length=68, null=True, verbose_name='վերնագր'),
        ),
    ]
