# Generated by Django 3.2.9 on 2022-03-13 15:42

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220311_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=froala_editor.fields.FroalaField(max_length=50, verbose_name='Մութքագրման դաշտ'),
        ),
    ]
