# Generated by Django 3.2.9 on 2022-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_contacts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Մեդիա',
                'verbose_name_plural': 'Մեդիա',
            },
        ),
    ]
