# Generated by Django 3.2.9 on 2022-03-21 16:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryfirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
                ('text', ckeditor.fields.RichTextField(verbose_name='տեքստ')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Գլղավոր-Կատեգորյ',
                'verbose_name_plural': 'Գլղավոր-Կատեգորյաներ',
            },
        ),
    ]
