# Generated by Django 3.2.9 on 2022-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_categoryfirst'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfirst',
            name='image',
            field=models.ImageField(default=1, upload_to='categoryfirst', verbose_name='նկար'),
            preserve_default=False,
        ),
    ]
