# Generated by Django 3.2.9 on 2022-03-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_categorylast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylast',
            options={'verbose_name': 'Յեկրերթական-Կատեգորյա', 'verbose_name_plural': 'Յեկրերթական-Կատեգորյանոր '},
        ),
    ]
