# Generated by Django 3.2.9 on 2022-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_comment_cha'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfirst',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
