# Generated by Django 3.2.9 on 2022-03-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_categoryfirst_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylast',
            old_name='key',
            new_name='keylast',
        ),
    ]
