# Generated by Django 4.0.2 on 2022-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_auto_20220326_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="name",
            field=models.TextField(max_length=50, verbose_name="Մութքագրման դաշտ"),
        ),
    ]
