# Generated by Django 4.0.2 on 2022-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_categoryfirst_text_en_categoryfirst_text_fa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryfirst",
            name="icon",
            field=models.ImageField(default=1, upload_to="icon", verbose_name="լոգո"),
            preserve_default=False,
        ),
    ]
