# Generated by Django 4.0.2 on 2022-04-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_categoryfirst_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="KeyCategori",
                to="main.categoryfirst",
                verbose_name="Կատեգորյաներ",
            ),
        ),
    ]
