# Generated by Django 4.0.2 on 2022-04-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_categoryfirst_text_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
