# Generated by Django 3.2.9 on 2022-04-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_shop_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
